---
version: "3.7"
services:
  traefik:
    container_name: ${DOMAIN_NAME}
    environment:
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}
    restart: always
    image: traefik
    networks:
      - mydomain
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/traefik:ro"
networks:
  mydomain:
    name: ${DOMAIN_NAME}